### ISSUE TITLE
Making app working with mongo fails

### ISSUE THREAD

**Issue by CristianCCIT** [akeneo/pim-community-standard#140]
I made the steps from here : http://docs.akeneo.com/master/installation/installation_workstation.html#installing-and-enabling-mongodb-support-in-akeneo withoud receiving errors.

I read that in the version 1.3 a parameter was changed : https://github.com/akeneo/pim-community-standard/blob/master/UPGRADE-1.3.md (you should update the documentation ... my opinion)

Changing that and making an composer update, i receive an error : 
```
Loading composer repositories with package information
Updating dependencies (including require-dev)                                      
Nothing to install or update
Package dflydev/markdown is abandoned, you should avoid using it. Use michelf/php-markdown instead.
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package friendsofsymfony/rest is abandoned, you should avoid using it. No replacement was suggested.
Generating autoload files
Updating the "app/config/parameters.yml" file
                                                                                
  [Symfony\Component\DependencyInjection\Exception\ParameterNotFoundException]  
  You have requested a non-existent parameter "mongodb_server". 

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-update-cmd event terminated with an exception
 
  [RuntimeException]                                                         
  An error occurred when executing the "'cache:clear --no-warmup'" command.
```
My configuration file looks like : 
```yaml
# This file is auto-generated during the composer install
parameters:
    database_driver: pdo_mysql
    database_host: localhost
    database_port: null
    database_name: akeneo_pim
    database_user: akeneo_pim
    database_password: akeneo_pim
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    pim_catalog_storage_driver: doctrine/mongodb-odm
    pim_catalog_product_storage_driver: doctrine/mongodb-odm
    mongodb_server: 'mongodb://localhost:27017'
    mongodb_database: akeneo_pim
```
